class Artist:
    def __init__(self, **kwargs):
        self.id = kwargs.get('artist_id')
        self.community_user_id = kwargs.get('community_user_id')
        self.name = kwargs.get('name')
        self.list_name = kwargs.get('list_name')
        self.is_online = kwargs.get('is_online')
        self.profile_nick_name = kwargs.get('profile_nick_name')
        self.profile_img_path = kwargs.get('profile_img_path')
        self.is_birthday = kwargs.get('is_birthday')
        self.group_name = kwargs.get('group_name')
        self.max_comment_count = kwargs.get('max_comment_count')
        self.community_id = kwargs.get('community_id')
        self.is_enabled = kwargs.get('is_enabled')
        self.has_new_to_fans = kwargs.get('has_new_to_fans')
        self.has_new_private_to_fans = kwargs.get('has_new_private_to_fans')
        self.to_fan_last_id = kwargs.get('to_fan_last_id')
        self.to_fan_last_created_at = kwargs.get('to_fan_last_created_at')
        self.to_fan_last_expire_in = kwargs.get('to_fan_last_expire_in')
        self.birthday_img_url = kwargs.get('birthday_img_url')
        self.community = []
        self.posts = []
